### PR TITLE
UI develop

### PR DESCRIPTION
**Pull request by kennes913**
An updated [version](https://dev.twitter.com/ads/version/1) of the Twitter Ads API was released recently. My changes focus on updating your library for use with newest version. 

I tried to keep consistent with your structure while attempting not to violate DRY. I added tests for new objects/functions, but the tests are far from thorough. 

In general, the vast majority of commits are additions; very few things were changed. 

Major additions include:
- Distinction between **synchronous** and **asynchronous** stats calls.
- A **create_async_jobs** method for posting new jobs for retrieval
- An **AsyncStatsAdapter** class for handling creation and retrieval
- **enum_utils**, the start of a few utility functions to be used for handling [ad enumerations](https://dev.twitter.com/ads/basics/enums).

### CODE REVIEW

**Comment by jdgillespie91** [comment]
Hi @kennes913,

I'll take a look at this pull request and aim to have it merged or closed within a week, so by Friday 13th May.

I should note that I no longer work for Essence (the team behind the essence-tech repo and the owner of this repository) so I don't have write access. That being said, I don't think it's actively maintained by Essence and so I'm sure they'll be happy to merge if I recommend it.

Thanks,

Jake

**Comment by jdgillespie91** [comment]
Hi @kennes913,

I've had a chance to look over and everything looks good. Since this library isn't in a polished state (even remotely), I'm only going to comment at a high level. Given your interest though, I might look into actively developing it again... I'll be in touch about that.

Anyway, here are some thoughts.

* I like that you've added `get_jobs`, `get_synchronous_stats` and `get_asynchronous_stats` to the API. I haven't used those resources in practice so it's difficult to comment meaningfully on your implementation, but it's the right place for those endpoints.
* I have a couple of comments on the way you've integrated the asynchronous resource.

    First, I don't think `retrieve` should be defined on `PreparedRequest` because then some resources are returned via `PreparedRequest.send` and some via `PreparedRequest.retrieve`. I'll give it some thought, but I suspect the answer is in the way we prepare the request. Perhaps we'll have two different types of prepared request; one for synchronous resources and one for asynchronous.

    Second, I would like to avoid inheritance if possible (`AsyncStatsAdapter` subclasses `Adapter`). I'm a fan of preferring _composition over inheritance_ because it stops us inheriting unexpected behaviour.

    ```python
    class Foo:
        def foo(self):
            pass

    class Bar:
        def foo(self):
            return Foo().foo()
    ```

* Regarding the `get_synchronous_stats` function in the api module, it would be good to reduce the number of arguments. The idea is that we make sensible assumptions in the functions we expose and, if the user needs more customisability, they can follow the patterns of the functions in the api to create their own requests.
* Finally, `enum_utils` looks like it is doing a lot more than the function lets on. I suspect we'll be able to refactor that to be more explicit but I've been away too long to step in right away. I'll spend some time with it soon and let you know what I think.

I hope the comments are clear. Please let me know your thoughts and whether you have a different opinion.

For now, I'm going to suggest that this be merged. As I say, this library is very much a work in progress and so introducing functionality is quite important right now. As we get a better sense of how it's used, we can begin to shape it a little more.

Thanks a bunch for the pull request!

**Comment by kennes913** [comment]
Hi @jdgillespie91,

I think this feedback makes a lot of sense. You're echoing similar thoughts I had in my head as I working through this.

One of the main struggles I had was the choice between composition and inheritance in **models.py**. Initially, I had added a post parameter to the send method in PreparedRequest along with additional logic calling a post method in Adapter class, but I thought it started to violate the idea of _sending_ something. It sounds like we may want to revert back to that to adhere to composition principles.

The **get_stats** and **get_asynchronous_stats** calls _do_ have too many parameters. I think we can add a more few api functions that cover most of querying. In **get_asynchronous_stats**, I think there may be a better way to request data asynchronously. Currently, I generate the jobs, sleep for some period and then request those jobs. 

Also, I'm not 100% certain if there's a need for **enum_utils.py**. This seems like a temporary solution to reduce unnecessary logic in **api.py**.

I like the idea of developing this out as there isn't a real polished version of the Twitter Ads endpoints out there yet. 

Thanks for the feedback. It's very helpful.

**Comment by jdgillespie91** [comment]
Hi @kennes913,

An update on things here. I've recommended that this be merged but since I don't have write access, I can't actually do it. Given that you've forked it and this repository has seen no changes for several months, I don't see any reason to chase Essence on merging it.

Instead, I would suggest the following. Continue to add to your forked repository, building out the functionality as you like. Separately, I'm looking at packaging this so that it can exist as a library in its own right. [Here's the repository](github.com/jdgillespie91/twads) for that. Further down the line, we could look at somehow combining the two.

If that appeals, or you'd like to hear more about the packaged repository, drop me [an email](mailto:jdgillespie91@gmail.com).

Thanks,

Jake

**Pull request closed without merging**
